---
- name: create docker container
  gather_facts: No
  hosts: localhost
  become: yes
  become_user: root
  tasks:
        - hostname:
            name: localhost

        # - name: create  diretory for mount netapp
        #   file:
        #     path: /tmp/mount1
        #     state: directory
        #     owner: root
        #     group: root
        #
        # - name: mount netapp
        #   mount:
        #     path: /tmp/mount1
        #     src: 10.110.10.27:/nc1_n2_jenkins_home/
        #     fstype: nfs
        #     state: mounted
        #
        # - name: create mount diretory
        #   file:
        #     path: /tmp/mount1/{{jenkins_hostname}}
        #     state: directory
        #     owner: root
        #     group: root

        - name: create jenkins home diretory
          file:
            path: /var/jenkins_home
            state: directory
            owner: root
            group: root

        # - name: mount netapp
        #   mount:
        #     path: /var/jenkins_home
        #     src: 10.110.10.27:/nc1_n2_jenkins_home/{{jenkins_hostname}}
        #     fstype: nfs
        #     state: mounted

        - name: create jenkins casc_config diretory
          file:
            path: /var/jenkins_home/casc_config
            state: directory
            owner: root
            group: root

        - name: copy jenkins configuration files
          copy:
            src: files/jenkins.yaml
            dest:  /var/jenkins_home/casc_config/jenkins.yaml

        - name: copy Pipeline Model Definition configuration
          copy:
            src: files/pipeline-model-definition.xml
            dest:  /var/jenkins_home/org.jenkinsci.plugins.pipeline.modeldefinition.config.GlobalConfig.xml

        - name: copy Syslog Logger configuration
          copy:
            src: files/SyslogLoggerPlugin.xml
            dest:  /var/jenkins_home/org.jenkinsci.plugins.sysloglogger.SyslogLoggerPlugin.xml

        - name: copy checkmarx configuration
          copy:
            src: files/com.checkmarx.jenkins.CxScanBuilder.xml
            dest:  /var/jenkins_home/com.checkmarx.jenkins.CxScanBuilder.xml

        - name: copy userContent directory with css files
          copy:
            src: files/userContent
            dest:  /var/jenkins_home

        - name: configure hostname
          replace:
            path: /var/jenkins_home/org.jenkinsci.plugins.sysloglogger.SyslogLoggerPlugin.xml
            regexp: 'JENKINS_HOSTNAME'
            replace: "{{ jenkins_hostname }}"
            backup: yes

        - name: configure hostname
          replace:
            path: /var/jenkins_home/casc_config/jenkins.yaml
            regexp: 'JENKINS_HOSTNAME'
            replace: "{{ jenkins_hostname }}"
            backup: yes

        - name: configure ip
          replace:
            path: /var/jenkins_home/casc_config/jenkins.yaml
            regexp: 'JENKINS_IP'
            replace: "{{ ansible_host }}"
            backup: yes

        - name: configure color
          replace:
            path: /var/jenkins_home/casc_config/jenkins.yaml
            regexp: 'JENKINS_COLOR'
            replace: "{{ jenkins_color }}"
            backup: yes

        - name: create docker container
          docker_container:
            name:  jenkins-master
            image: docker-virtual/allot-jenkins-master:{{JENKINS_VERSION}}
            dns_search_domains:
               - ALLOT.LOCAL
               - rdlab.local
            dns_servers:
               - 172.18.1.10
               - 172.17.1.10
               - 10.110.3.10
               - 10.110.3.11
            ports:
             - "80:8080"
             - "8080:8080"
             - "50000:50000"
            env:
              JAVA_OPTS: "-Xmx2048m -XX:MaxPermSize=512m  -DsessionTimeout=10080 -Dhudson.model.DirectoryBrowserSupport.CSP=\"img-src 'self'; style-src 'self' 'unsafe-inline';\" -Djenkins.install.runSetupWizard=false "
              #JAVA_OPTS: "-Xmx6144m -Xms512m -Djava.awt.headless=true -Djava.util.logging.config.file=/var/jenkins_home/log.properties  -Dhudson.model.ParametersAction.keepUndefinedParameters=true"
              CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_config"
              JENKINS_HOSTNAME: "{{ jenkins_hostname }}"
            volumes:
              - "/var/jenkins_home:/var/jenkins_home"
            user: 0:0
            restart_policy: always
