- name: copy all ssh key to Servers a
  hosts: all
  remote_user: root
  gather_facts: no
  become: true
  become_method: su
  become_user: root

  tasks:
    - name: Write the new ec2 instance host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ ansible_ssh_host }} >> ~/.ssh/id_rsa"
      register: check_ssh
      ignore_errors: True
    - name: copy id_rsa.pub to all nodes
      #when: check_ssh is failed
      connection: local
      shell: "sshpass -p root12  ssh-copy-id -i /root/.ssh/id_rsa root@{{ ansible_ssh_host }}"
      ignore_errors: True
