- name: copy all ssh key to Servers a
  hosts: all
  remote_user: root
  gather_facts: no
  become: true
  become_method: su
  become_user: root

  tasks:
    - name: Write the new ec2 instance host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ ansible_ssh_host }} >> ~/.ssh/known_hosts"
      register: check_ssh
      ignore_errors: True
    - name: copy id_rsa.pub to all nodes
      #when: check_ssh is failed
      connection: local
      shell: "sshpass -p root12  ssh-copy-id -i /root/.ssh/id_rsa root@{{ ansible_ssh_host }}"
      ignore_errors: True

- name: Install docker
  hosts: all
  remote_user: root
  gather_facts: no
  become: true
  become_method: su
  become_user: root

  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
      become: yes
