jenkins_app:
  image: jenkins/jenkins:2.164.3
  container_name: jenkins_master
  restart: always
  ports:
   - "80:8080"
   - "8080:8080"
   - "50000:50000"
  environment:
    JAVA_OPTS: "-Xmx2048m -XX:MaxPermSize=512m  -DsessionTimeout=10080 -Dhudson.model.DirectoryBrowserSupport.CSP=\"img-src 'self'; style-src 'self' 'unsafe-inline';\" -Djenkins.install.runSetupWizard=false "
    #JAVA_OPTS: "-Xmx6144m -Xms512m -Djava.awt.headless=true -Djava.util.logging.config.file=/var/jenkins_home/log.properties  -Dhudson.model.ParametersAction.keepUndefinedParameters=true"
    CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_config"
    JENKINS_HOSTNAME: "10.110.4.25"
  volumes:
    - "/var/jenkins_home:/var/jenkins_home"
  user: 0:0
